# Generated by Django 5.2.6 on 2025-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_customer_alter_menu_group_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(null=True, upload_to='customers', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ImageField(null=True, upload_to='menus', verbose_name='Изображение'),
        ),
    ]
