# Generated by Django 5.2.6 on 2025-11-30 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_options_remove_category_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.TextField(null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(null=True, upload_to='customers', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Готов'), ('CANCELLED', 'Отменён')], default='NEW', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menu', verbose_name='Позиция меню'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
