# Generated by Django 5.2.6 on 2025-12-01 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_price_alter_customer_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор')], default='USER', max_length=16, verbose_name='Роль')),
                ('twofa_passed', models.BooleanField(default=False, verbose_name='2FA пройдена')),
                ('twofa_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='2FA истекает')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
