# Generated by Django 6.0 on 2025-12-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menu_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Готов'), ('CANCELLED', 'Отменён')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
